apiVersion: v1
kind: ConfigMap
metadata:
  name: security-policy
  namespace: accu-platform
data:
  # Network Security Policies
  network-policy.yaml: |
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: backend-network-policy
      namespace: accu-platform
    spec:
      podSelector:
        matchLabels:
          app: backend
      policyTypes:
      - Ingress
      - Egress
      ingress:
      - from:
        - podSelector:
            matchLabels:
              app: frontend
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        ports:
        - protocol: TCP
          port: 3000
      egress:
      - to:
        - podSelector:
            matchLabels:
              app: postgres
        ports:
        - protocol: TCP
          port: 5432
      - to:
        - podSelector:
            matchLabels:
              app: redis
        ports:
        - protocol: TCP
          port: 6379
      - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
        ports:
        - protocol: TCP
          port: 53
          - protocol: UDP
          port: 53
          - protocol: TCP
          port: 9153
          - protocol: UDP
          port: 9153

  # Pod Security Policies
  pod-security-policy.yaml: |
    apiVersion: policy/v1beta1
    kind: PodSecurityPolicy
    metadata:
      name: accu-platform-psp
      namespace: accu-platform
    spec:
      privileged: false
      allowPrivilegeEscalation: false
      requiredDropCapabilities:
        - ALL
      volumes:
        - 'configMap'
        - 'emptyDir'
        - 'projected'
        - 'secret'
        - 'downwardAPI'
        - 'persistentVolumeClaim'
      hostNetwork: false
      hostIPC: false
      hostPID: false
      runAsUser:
        rule: 'MustRunAsNonRoot'
      seLinux:
        rule: 'RunAsAny'
      fsGroup:
        rule: 'MustRunAs'
        ranges:
          - min: 1
            max: 65535
      readOnlyRootFilesystem: true

  # Security Context Constraints
  security-context.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: security-context
      namespace: accu-platform
    data:
      backend-security-context.yaml: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: backend
          namespace: accu-platform
        spec:
          template:
            spec:
              securityContext:
                runAsNonRoot: true
                runAsUser: 1001
                fsGroup: 1001
              containers:
              - name: backend
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities:
                    drop:
                    - ALL
                  runAsNonRoot: true
                  runAsUser: 1001

  # RBAC Security Policies
  rbac-policy.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: rbac-policy
      namespace: accu-platform
    data:
      service-account.yaml: |
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: accu-platform-sa
          namespace: accu-platform
        automountServiceAccountToken: false
      cluster-role.yaml: |
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        metadata:
          name: accu-platform-role
        rules:
        - apiGroups: [""]
          resources: ["configmaps", "secrets", "services"]
          verbs: ["get", "list", "watch"]
        - apiGroups: ["apps"]
          resources: ["deployments"]
          verbs: ["get", "list", "watch"]
        cluster-role-binding.yaml: |
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: accu-platform-binding
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: accu-platform-role
        subjects:
        - kind: ServiceAccount
          name: accu-platform-sa
          namespace: accu-platform

  # Security Scanning Configuration
  security-scanning.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: security-scanning
      namespace: accu-platform
    data:
      trivy-config.yaml: |
        security:
          scanning:
            enabled: true
            schedule: "0 2 * * *"  # Daily at 2 AM
            severity_threshold: "HIGH"
            fail_on_high: true
            ignore_unfixed: true
            format: "sarif"
            output: "/tmp/trivy-results.sarif"
      
      snyk-config.yaml: |
        security:
          snyk:
            enabled: true
            test_dependencies: true
            test_container_images: true
            severity_threshold: "high"
            fail_on_issues: true
            monitor_project: true

  # Compliance Policies
  compliance-policy.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: compliance-policy
      namespace: accu-platform
    data:
      cis-benchmarks.yaml: |
        compliance:
          cis_benchmarks:
            enabled: true
            version: "1.6"
            controls:
              - "1.1.1"  # Ensure the cluster admin group is not used
              - "1.2.9"  # Ensure that the --kubelet-https argument is set to true
              - "1.3.1"  # Ensure that the --anonymous-auth argument is set to false
              - "1.3.2"  # Ensure that the --authorization-mode argument is not set to AlwaysAllow
              - "1.4.1"  # Ensure that a network policy is applied to appropriate namespaces
              - "2.1"    # Ensure that the cluster is created with a minimum number of nodes
              - "2.2"    # Ensure that all data is encrypted at rest
              - "2.3"    # Ensure that encryption keys are rotated regularly
      
      nist-800-53.yaml: |
        compliance:
          nist_800_53:
            enabled: true
            controls:
              - "AC-2"   # Account Management
              - "AC-3"   # Access Enforcement
              - "AC-6"   # Least Privilege
              - "AU-2"   # Audit Events
              - "AU-6"   # Audit Review
              - "AU-8"   # Time Stamps
              - "CA-3"   # System Information Exchange
              - "CM-2"   # Baseline Configuration
              - "CM-3"   # Configuration Change Control
              - "CM-6"   # Configuration Settings
              - "CP-2"   # Contingency Plan
              - "CP-4"   # Contingency Plan Testing
              - "CP-6"   # Alternate Storage Site
              - "CP-7"   # Alternate Processing Site
              - "CP-8"   # Telecommunications Services
              - "CP-9"   # Information System Backup
              - "CP-10"  # Information System Recovery and Reconstitution
              - "IA-2"   # Identification and Authentication
              - "IR-1"   # Incident Response Policy and Procedures
              - "IR-4"   # Incident Handling
              - "IR-5"   # Incident Monitoring
              - "MA-4"   # Nonlocal Maintenance
              - "MP-6"   # Media Sanitization
              - "PE-3"   # Physical Access Control
              - "PL-2"   # Security Planning
              - "PM-9"   # Risk Management Strategy
              - "RA-3"   # Risk Assessment
              - "RA-5"   # Vulnerability Monitoring and Scanning
              - "SC-7"   # Boundary Protection
              - "SC-8"   # Transmission Confidentiality and Integrity
              - "SC-13"  # Cryptographic Protection
              - "SC-28"  # Protection of Information at Rest
              - "SI-2"   # Flaw Remediation
              - "SI-4"   # System Monitoring
              - "SI-7"   # Software, Firmware, and Information Integrity
              - "SR-3"   # Supply Chain Controls and Processes

  # Security Incident Response
  incident-response.yaml: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: incident-response
      namespace: accu-platform
    data:
      security-incident-response.yaml: |
        incident_response:
          procedures:
            detection:
              - "Monitor security alerts and logs"
              - "Analyze intrusion detection system alerts"
              - "Review access logs for suspicious activity"
            
            containment:
              - "Isolate affected systems"
              - "Block malicious IP addresses"
              - "Revoke compromised credentials"
              - "Disable affected user accounts"
            
            eradication:
              - "Remove malware and malicious artifacts"
              - "Patch vulnerabilities"
              - "Update security controls"
              - "Restore from clean backups if necessary"
            
            recovery:
              - "Restore systems to normal operation"
              - "Monitor for signs of recurrence"
              - "Update incident response procedures"
              - "Conduct post-incident review"
          
          escalation_matrix:
            severity:
              critical: ["CTO", "CISO", "DevOps Team"]
              high: ["Security Team", "DevOps Team"]
              medium: ["Security Team"]
              low: ["Security Team"]
          
          communication_plan:
            internal:
O"
              - "CISO"
              - "Security Team"
              - "CT              - "Dev - "Development Team"
            
            external:
              - "Law enforcement (Ops Team"
             if required)"
              - "Regulatory bodies (if required)"
              - "Customers (if data breach)"
              - "Third-party vendors (if affected)"
          
          documentation:
            - "Incident timeline"
            - "Actions taken"
            - "Systems affected"
            - "Data compromised"
            - "Root cause analysis"
            - "Lessons learned"